[Unit]
Requires=ufw.service
Wants=vps-tier-moscow-client-policy.service
After=ufw.service vps-tier-moscow-client-policy.service

[Service]
ExecStartPre=/usr/bin/systemctl is-active --quiet vps-tier-moscow-client-policy.service
