#!/usr/bin/env bash
set -Eeuo pipefail

SOURCE_HEAD="${VPS_TIER_SOURCE_HEAD:-}"
EXPECTED_IPV4="147.45.184.140"
EXPECTED_CODENAME="noble"
IFACE="awg-client"
PORT="443"
SERVER_ADDR="10.71.0.1/24"
CLIENT_SUBNET="10.71.0.0/24"
CLIENT_ADDR="10.71.0.2/32"
CONFIG_DIR="/etc/amnezia/amneziawg"
TARGET_CONF="$CONFIG_DIR/$IFACE.conf"
TARGET_TMP="${TARGET_CONF}.vps-tier.tmp"
MATERIAL_DIR="$CONFIG_DIR/vps-tier/$IFACE"
SERVER_KEY="$MATERIAL_DIR/server.key"
SERVER_PUB="$MATERIAL_DIR/server.pub"
CLIENT_KEY="$MATERIAL_DIR/iphone.key"
CLIENT_PUB="$MATERIAL_DIR/iphone.pub"
PARAMS_FILE="$MATERIAL_DIR/params.env"
UNIT="awg-quick@$IFACE.service"
STATE_DIR="/var/lib/vps-tier/moscow-awg-client-termination"
STATE_FILE="$STATE_DIR/state.env"
EVIDENCE_FILE="$STATE_DIR/evidence.md"
BACKUP_ROOT="/var/backups/vps-tier/moscow-awg-client-termination/apply"
UFW_COMMENT="vps-tier-awg-client-ingress"
TMP_DIR=""
BACKUP_DIR=""
MATERIAL_CREATED=0
CONFIG_CREATED=0
UFW_CREATED=0
UNIT_TOUCHED=0

fail() { echo "ERROR: $*" >&2; return 1; }
require_cmd() { command -v "$1" >/dev/null 2>&1 || fail "missing command: $1"; }
host_ok() { ip -4 -o addr show scope global | awk '{print $4}' | cut -d/ -f1 | grep -Fx "$EXPECTED_IPV4" >/dev/null; }
ufw_active() { ufw status 2>/dev/null | grep -x 'Status: active' >/dev/null; }
ufw_has_marker() { ufw status numbered 2>/dev/null | grep -F "$UFW_COMMENT" >/dev/null; }
remove_owned_ufw_rule() {
  while ufw_has_marker; do
    num="$(ufw status numbered | sed -nE "s/^\[[[:space:]]*([0-9]+)\].*${UFW_COMMENT}.*/\1/p" | head -n1)"
    [ -n "$num" ] || return 1
    ufw --force delete "$num" >/dev/null
  done
}
snapshot_nat() { iptables-save -t nat | sed -E '/^# (Generated by iptables-save|Completed on) /d'; }
snapshot_units() {
  out="$1"; : > "$out"
  for unit in ssh.socket nginx.service postgresql.service flowise-proxy.service vps-backup-relay.socket wg-quick@wg-backbone.service; do
    printf 'UNIT=%s\n' "$unit" >> "$out"
    systemctl show "$unit" -p LoadState -p ActiveState -p SubState -p MainPID --no-pager 2>/dev/null >> "$out" || true
  done
}
assert_required_units() {
  for unit in ssh.socket nginx.service postgresql.service flowise-proxy.service vps-backup-relay.socket wg-quick@wg-backbone.service; do
    systemctl is-active --quiet "$unit" || fail "protected unit inactive: $unit"
  done
}
assert_no_client_subnet_overlap() {
  python3 -c '
import ipaddress, sys
target = ipaddress.ip_network(sys.argv[1], strict=False)
for raw in sys.stdin:
    value = raw.strip()
    if not value:
        continue
    try:
        network = ipaddress.ip_network(value, strict=False)
    except ValueError:
        continue
    if target.overlaps(network):
        print(f"ERROR: client subnet overlaps existing prefix {network}", file=sys.stderr)
        sys.exit(1)
' "$CLIENT_SUBNET" < <(
    ip -4 -o addr show | awk '{print $4}'
    ip -4 route show table all | awk '$1 ~ /^[0-9]+\./ {print $1}'
  )
}
cleanup() {
  [ -z "$TMP_DIR" ] || rm -rf "$TMP_DIR"
  rm -f "$TARGET_TMP"
}
rollback_on_error() {
  rc=$?; trap - ERR; set +e
  echo "ERROR: Moscow AWG client termination apply failed; reverting task-owned changes" >&2
  if [ "$UNIT_TOUCHED" -eq 1 ]; then systemctl disable --now "$UNIT" >/dev/null 2>&1 || true; fi
  ip link show "$IFACE" >/dev/null 2>&1 && ip link delete "$IFACE" >/dev/null 2>&1 || true
  if [ "$UFW_CREATED" -eq 1 ]; then remove_owned_ufw_rule || true; fi
  if [ "$CONFIG_CREATED" -eq 1 ]; then rm -f "$TARGET_CONF"; fi
  if [ "$MATERIAL_CREATED" -eq 1 ]; then rm -rf "$MATERIAL_DIR"; fi
  rollback_ok=1
  ip link show "$IFACE" >/dev/null 2>&1 && rollback_ok=0
  ufw_has_marker && rollback_ok=0
  [ -e "$TARGET_CONF" ] && rollback_ok=0
  [ -e "$MATERIAL_DIR" ] && rollback_ok=0
  if [ "$rollback_ok" -eq 1 ]; then
    rm -rf "$STATE_DIR"
  else
    echo "ERROR: automatic rollback incomplete; managed state retained" >&2
  fi
  exit "$rc"
}
trap cleanup EXIT

[ "${EUID:-$(id -u)}" -eq 0 ] || fail "run as root"
[[ "$SOURCE_HEAD" =~ ^[0-9a-f]{40}$ ]] || fail "VPS_TIER_SOURCE_HEAD must be a full lowercase commit SHA"
for cmd in awk awg awg-quick cmp cut date dpkg-query grep head install ip iptables-save mktemp modinfo mv ping python3 sed sha256sum ss stat sysctl systemctl tr ufw; do require_cmd "$cmd"; done
host_ok || fail "host identity mismatch"
. /etc/os-release
[ "${ID:-}" = ubuntu ] && [ "${VERSION_CODENAME:-}" = "$EXPECTED_CODENAME" ] || fail "OS/suite mismatch"
[ "$(dpkg --print-architecture)" = amd64 ] || fail "architecture mismatch"
[ -d "$CONFIG_DIR" ] || fail "AmneziaWG config directory missing: $CONFIG_DIR"
systemctl cat awg-quick@.service >/dev/null 2>&1 || fail "awg-quick systemd template missing"
[ "$(modinfo -F version amneziawg)" = "3.0.20260805" ] || fail "unexpected amneziawg module version"
[ -r /var/lib/vps-tier/moscow-awg-toolchain/state.env ] || fail "managed AWG toolchain state missing"
[ -r /var/lib/vps-tier/wireguard-backbone/moscow/state.env ] || fail "managed backbone state missing"
[ ! -e "$STATE_DIR" ] || fail "managed Stage-5 state already exists"
[ ! -e "$TARGET_CONF" ] || fail "AWG client config already exists"
[ ! -e "$MATERIAL_DIR" ] || fail "AWG client material directory already exists"
! ip link show "$IFACE" >/dev/null 2>&1 || fail "AWG client interface already exists"
! systemctl is-active --quiet "$UNIT" || fail "AWG client unit already active"
! systemctl is-enabled --quiet "$UNIT" || fail "AWG client unit already enabled"
ss -H -lun "sport = :$PORT" | grep . >/dev/null && fail "udp/$PORT is occupied"
ufw_active || fail "UFW must be active"
ufw_has_marker && fail "managed AWG ingress UFW rule already exists"
ufw status numbered | grep -E '443/udp|10\.71\.|awg-client' >/dev/null && fail "unmanaged AWG/client-related UFW rule exists"
[ "$(sysctl -n net.ipv4.ip_forward)" = 0 ] || fail "Moscow IPv4 forwarding must remain 0 for Stage 5"
[ "$(sysctl -n net.ipv6.conf.all.forwarding)" = 0 ] || fail "Moscow IPv6 forwarding must remain 0"
assert_no_client_subnet_overlap || fail "client subnet overlaps current Moscow state"
assert_required_units

BACKUP_ID="$(date -u +%Y%m%dT%H%M%SZ)"
BACKUP_DIR="$BACKUP_ROOT/$BACKUP_ID"
mkdir -p "$BACKUP_DIR" "$STATE_DIR"
chmod 0700 "$BACKUP_DIR" "$STATE_DIR"
DEFAULT_ROUTE_BEFORE="$(ip -4 route show default)"
BACKBONE_ROUTE_BEFORE="$(ip -4 route show 10.70.0.0/30)"
IPV4_FORWARD_BEFORE="$(sysctl -n net.ipv4.ip_forward)"
IPV6_FORWARD_BEFORE="$(sysctl -n net.ipv6.conf.all.forwarding)"
snapshot_nat > "$BACKUP_DIR/nat.before"
snapshot_units "$BACKUP_DIR/units.before"
ufw status numbered > "$BACKUP_DIR/ufw.before"

trap rollback_on_error ERR
mkdir -p "$MATERIAL_DIR"
chmod 0700 "$CONFIG_DIR/vps-tier" "$MATERIAL_DIR"
MATERIAL_CREATED=1
umask 077
awg genkey > "$SERVER_KEY"
awg pubkey < "$SERVER_KEY" > "$SERVER_PUB"
awg genkey > "$CLIENT_KEY"
awg pubkey < "$CLIENT_KEY" > "$CLIENT_PUB"
python3 - "$PARAMS_FILE" <<'PY'
import secrets, sys
path = sys.argv[1]
jc = 4 + secrets.randbelow(9)
s1 = 15 + secrets.randbelow(136)
while True:
    s2 = 15 + secrets.randbelow(136)
    if s1 + 56 != s2:
        break
hs = []
while len(hs) < 4:
    value = 5 + secrets.randbelow(2147483643)
    if value not in hs:
        hs.append(value)
with open(path, "w", encoding="ascii") as f:
    f.write(f"Jc={jc}\nJmin=8\nJmax=80\nS1={s1}\nS2={s2}\n")
    for i, value in enumerate(hs, 1):
        f.write(f"H{i}={value}\n")
PY
chmod 0600 "$SERVER_KEY" "$SERVER_PUB" "$CLIENT_KEY" "$CLIENT_PUB" "$PARAMS_FILE"
[ "$(stat -c '%U:%G %a' "$SERVER_KEY")" = "root:root 600" ] || fail "server key permissions invalid"
[ "$(stat -c '%U:%G %a' "$CLIENT_KEY")" = "root:root 600" ] || fail "client key permissions invalid"
# shellcheck disable=SC1090
. "$PARAMS_FILE"

TMP_DIR="$(mktemp -d /tmp/vps-tier-awg-client.XXXXXX)"
chmod 0700 "$TMP_DIR"
TMP_CONF="$TMP_DIR/$IFACE.conf"
SERVER_PRIVATE="$(tr -d '\r\n' < "$SERVER_KEY")"
CLIENT_PUBLIC="$(tr -d '\r\n' < "$CLIENT_PUB")"
cat > "$TMP_CONF" <<CONFIG
[Interface]
Address = $SERVER_ADDR
ListenPort = $PORT
PrivateKey = $SERVER_PRIVATE
MTU = 1280
Jc = $Jc
Jmin = $Jmin
Jmax = $Jmax
S1 = $S1
S2 = $S2
H1 = $H1
H2 = $H2
H3 = $H3
H4 = $H4

[Peer]
PublicKey = $CLIENT_PUBLIC
AllowedIPs = $CLIENT_ADDR
CONFIG
unset SERVER_PRIVATE CLIENT_PUBLIC Jc Jmin Jmax S1 S2 H1 H2 H3 H4
chmod 0600 "$TMP_CONF"
awg-quick strip "$TMP_CONF" >/dev/null
install -o root -g root -m 0600 "$TMP_CONF" "$TARGET_TMP"
mv -f "$TARGET_TMP" "$TARGET_CONF"
CONFIG_CREATED=1

ufw allow from any to "$EXPECTED_IPV4" port "$PORT" proto udp comment "$UFW_COMMENT" >/dev/null
UFW_CREATED=1
ufw_has_marker || fail "failed to verify AWG ingress UFW rule"

UNIT_TOUCHED=1
systemctl enable --now "$UNIT" >/dev/null
systemctl is-active --quiet "$UNIT" || fail "$UNIT is not active"
systemctl is-enabled --quiet "$UNIT" || fail "$UNIT is not enabled"
ip link show "$IFACE" >/dev/null 2>&1 || fail "AWG client interface missing"
ip -4 addr show dev "$IFACE" | grep -F "$SERVER_ADDR" >/dev/null || fail "AWG server address missing"
[ "$(awg show "$IFACE" listen-port)" = "$PORT" ] || fail "AWG listen port mismatch"
SERVER_PUBLIC_EXPECTED="$(tr -d '\r\n' < "$SERVER_PUB")"
CLIENT_PUBLIC_EXPECTED="$(tr -d '\r\n' < "$CLIENT_PUB")"
[ "$(awg show "$IFACE" public-key)" = "$SERVER_PUBLIC_EXPECTED" ] || fail "AWG server public key mismatch"
[ "$(awg show "$IFACE" peers)" = "$CLIENT_PUBLIC_EXPECTED" ] || fail "AWG client peer mismatch"
awg show "$IFACE" allowed-ips | grep -F "$CLIENT_PUBLIC_EXPECTED" | grep -F "$CLIENT_ADDR" >/dev/null || fail "AWG client AllowedIPs mismatch"
ss -H -lun "sport = :$PORT" | grep . >/dev/null || fail "udp/$PORT listener absent after AWG start"
ip -4 route show "$CLIENT_SUBNET" | grep -F "dev $IFACE" >/dev/null || fail "client connected route missing"

[ "$(ip -4 route show default)" = "$DEFAULT_ROUTE_BEFORE" ] || fail "default route changed"
[ "$(ip -4 route show 10.70.0.0/30)" = "$BACKBONE_ROUTE_BEFORE" ] || fail "backbone route changed"
[ "$(sysctl -n net.ipv4.ip_forward)" = "$IPV4_FORWARD_BEFORE" ] || fail "IPv4 forwarding changed"
[ "$(sysctl -n net.ipv6.conf.all.forwarding)" = "$IPV6_FORWARD_BEFORE" ] || fail "IPv6 forwarding changed"
snapshot_nat > "$BACKUP_DIR/nat.after"
cmp -s "$BACKUP_DIR/nat.before" "$BACKUP_DIR/nat.after" || fail "NAT table changed"
ping -c 1 -W 2 10.70.0.2 >/dev/null || fail "backbone ping failed after AWG apply"
snapshot_units "$BACKUP_DIR/units.after"
cmp -s "$BACKUP_DIR/units.before" "$BACKUP_DIR/units.after" || fail "protected unit state changed"
assert_required_units
ufw status numbered > "$BACKUP_DIR/ufw.after"
CONFIG_SHA="$(sha256sum "$TARGET_CONF" | awk '{print $1}')"

cat > "$STATE_FILE" <<STATE
owner=vps-tier
source_head=$SOURCE_HEAD
applied_at_utc=$BACKUP_ID
backup_set=$BACKUP_DIR
interface=$IFACE
server_address=$SERVER_ADDR
client_address=$CLIENT_ADDR
listen_port=$PORT
config_path=$TARGET_CONF
config_sha256=$CONFIG_SHA
material_dir=$MATERIAL_DIR
server_public_key_file=$SERVER_PUB
client_public_key_file=$CLIENT_PUB
client_private_key_file=$CLIENT_KEY
params_file=$PARAMS_FILE
ufw_rule_owned=yes
STATE
chmod 0600 "$STATE_FILE"

cat > "$EVIDENCE_FILE" <<EVIDENCE
# Moscow AmneziaWG Client Termination — Apply Evidence

- UTC: $(date -u +%Y-%m-%dT%H:%M:%SZ)
- Source Git HEAD: $SOURCE_HEAD
- Host IPv4: $EXPECTED_IPV4
- Interface: $IFACE
- Server address: $SERVER_ADDR
- First client address: $CLIENT_ADDR
- Listen port: udp/$PORT
- MTU: 1280
- AWG server/client key material created server-locally: yes
- AWG parameters generated server-locally: yes
- Private/profile-bearing material printed or committed: no
- Managed UFW IPv4 ingress rule: yes
- Interface active and enabled: yes
- Client peer configured: yes
- Client handshake: deferred until client profile stage
- Default route changed: no
- IPv4 forwarding changed: no (remains 0)
- IPv6 forwarding changed: no (remains 0)
- Moscow NAT table changed: no
- Backbone ping after apply: passed
- Protected unit state changed: no
- Client Internet forwarding: not enabled in Stage 5
- Backup set: $BACKUP_DIR
- Secrets recorded: no
EVIDENCE
chmod 0600 "$EVIDENCE_FILE"

trap - ERR
MATERIAL_CREATED=0; CONFIG_CREATED=0; UFW_CREATED=0; UNIT_TOUCHED=0

echo "DONE: Moscow AWG client termination applied"
echo "INTERFACE=$IFACE"
echo "ADDRESS=$SERVER_ADDR"
echo "CLIENT_ADDRESS=$CLIENT_ADDR"
echo "UDP_PORT=$PORT"
echo "IPV4_FORWARDING=unchanged_0"
echo "CLIENT_HANDSHAKE=deferred"
echo "CLIENT_INTERNET=blocked_until_stage6"
echo "EVIDENCE_FILE=$EVIDENCE_FILE"
echo "BACKUP_SET=$BACKUP_DIR"
