#!/usr/bin/env bash
set -Eeuo pipefail

SOURCE_HEAD="${VPS_TIER_SOURCE_HEAD:-}"
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
EXPECTED_IPV4="147.45.184.140"
EXPECTED_CODENAME="noble"
CLIENT_SUBNET="10.71.0.0/24"
AWG_IF="awg-client"
WG_IF="wg-backbone"
WAN_IF="eth0"
TABLE_ID="1071"
RULE_PRIORITY="10710"
KZ_TUNNEL_IP="10.70.0.2"
KZ_PUBLIC_KEY="SXeu14QxklfRSCu7r/ePgYYPwasKobsk8jUWAsIeGhs="
BASE_ALLOWED="10.70.0.2/32"
APPLIED_ALLOWED="0.0.0.0/0"
WG_CONF="/etc/wireguard/wg-backbone.conf"
WG_TMP="${WG_CONF}.vps-tier-stage6.tmp"
SYSCTL_FILE="/etc/sysctl.d/99-vps-tier-moscow-client-routing.conf"
POLICY_RUNTIME="/usr/local/libexec/vps-tier/moscow-client-policy-runtime"
POLICY_UNIT_NAME="vps-tier-moscow-client-policy.service"
POLICY_UNIT="/etc/systemd/system/$POLICY_UNIT_NAME"
AWG_DROPIN_DIR="/etc/systemd/system/awg-quick@awg-client.service.d"
AWG_DROPIN="$AWG_DROPIN_DIR/20-vps-tier-fail-closed.conf"
POLICY_SOURCE="$SCRIPT_DIR/moscow_client_policy_runtime.sh"
POLICY_UNIT_SOURCE="$SCRIPT_DIR/../templates/systemd/vps-tier-moscow-client-policy.service"
AWG_DROPIN_SOURCE="$SCRIPT_DIR/../templates/systemd/awg-client-fail-closed.conf"
STATE_DIR="/var/lib/vps-tier/moscow-fail-closed-routing"
STATE_FILE="$STATE_DIR/state.env"
EVIDENCE_FILE="$STATE_DIR/evidence.md"
BACKUP_ROOT="/var/backups/vps-tier/moscow-fail-closed-routing/apply"
UFW_FORWARD_COMMENT="vps-tier-moscow-client-forward"
UFW_DENY_COMMENT="vps-tier-moscow-client-no-fallback"
BACKUP_DIR=""
TMP_DIR=""
BASE_CONFIG_SHA=""
APPLIED_CONFIG_SHA=""
CONFIG_CHANGED=0
WG_RUNTIME_CHANGED=0
POLICY_FILES_INSTALLED=0
POLICY_STARTED=0
UFW_FORWARD_ADDED=0
UFW_DENY_ADDED=0
SYSCTL_CREATED=0
FORWARDING_CHANGED=0

fail() { echo "ERROR: $*" >&2; return 1; }
require_cmd() { command -v "$1" >/dev/null 2>&1 || fail "missing command: $1"; }
host_ok() { ip -4 -o addr show scope global | awk '{print $4}' | cut -d/ -f1 | grep -Fx "$EXPECTED_IPV4" >/dev/null; }
runtime_allowed_ips() { wg show "$WG_IF" dump | awk -F '\t' -v key="$KZ_PUBLIC_KEY" '$1==key {print $4}'; }
ufw_has_marker() { ufw status numbered 2>/dev/null | grep -F "$1" >/dev/null; }
remove_ufw_marker() {
  marker="$1"
  while ufw_has_marker "$marker"; do
    num="$(ufw status numbered | sed -nE "s/^\[[[:space:]]*([0-9]+)\].*${marker}.*/\1/p" | head -n1)"
    [ -n "$num" ] || return 1
    ufw --force delete "$num" >/dev/null
  done
}
snapshot_nat() { iptables-save -t nat | sed -E '/^# (Generated by iptables-save|Completed on) /d'; }
snapshot_units() {
  out="$1"; : > "$out"
  for unit in ssh.socket nginx.service postgresql.service flowise-proxy.service vps-backup-relay.socket wg-quick@wg-backbone.service awg-quick@awg-client.service; do
    printf 'UNIT=%s\n' "$unit" >> "$out"
    systemctl show "$unit" -p LoadState -p ActiveState -p SubState -p MainPID --no-pager 2>/dev/null >> "$out" || true
  done
}
assert_required_units() {
  for unit in ssh.socket nginx.service postgresql.service flowise-proxy.service vps-backup-relay.socket wg-quick@wg-backbone.service awg-quick@awg-client.service; do
    systemctl is-active --quiet "$unit" || fail "protected unit inactive: $unit"
  done
}
exact_policy_rule() {
  ip -4 rule show | awk -v p="${RULE_PRIORITY}:" '$1==p {print $1, $2, $3, $4, $5}' |
    grep -Fx "${RULE_PRIORITY}: from ${CLIENT_SUBNET} lookup ${TABLE_ID}" >/dev/null
}
remove_policy_barrier() {
  while exact_policy_rule; do
    ip -4 rule del priority "$RULE_PRIORITY" from "$CLIENT_SUBNET" lookup "$TABLE_ID" 2>/dev/null || break
  done
  ip -4 route del prohibit default table "$TABLE_ID" metric 32760 2>/dev/null || true
}
assert_no_forwarding_persistence() {
  found="$(grep -RhsE '^[[:space:]]*(net\.ipv4\.ip_forward|net\.ipv6\.conf\.all\.forwarding)[[:space:]]*=' \
    /etc/sysctl.conf /etc/sysctl.d /run/sysctl.d /usr/local/lib/sysctl.d /usr/lib/sysctl.d /lib/sysctl.d 2>/dev/null || true)"
  [ -z "$found" ] || fail "pre-existing persistent IPv4/IPv6 forwarding assignment exists"
}
cleanup() { [ -z "$TMP_DIR" ] || rm -rf "$TMP_DIR"; rm -f "$WG_TMP"; }
rollback_on_error() {
  rc=$?; trap - ERR; set +e
  echo "ERROR: Moscow fail-closed routing apply failed; reverting task-owned changes" >&2
  sysctl -w net.ipv4.ip_forward=0 >/dev/null 2>&1 || true
  FORWARDING_CHANGED=0
  [ "$UFW_FORWARD_ADDED" -eq 0 ] || remove_ufw_marker "$UFW_FORWARD_COMMENT" || true
  [ "$UFW_DENY_ADDED" -eq 0 ] || remove_ufw_marker "$UFW_DENY_COMMENT" || true
  ip -4 route del default dev "$WG_IF" table "$TABLE_ID" metric 10 2>/dev/null || true
  if [ "$WG_RUNTIME_CHANGED" -eq 1 ] && ip link show "$WG_IF" >/dev/null 2>&1; then
    wg set "$WG_IF" peer "$KZ_PUBLIC_KEY" allowed-ips "$BASE_ALLOWED" >/dev/null 2>&1 || true
  fi
  if [ "$CONFIG_CHANGED" -eq 1 ] && [ -r "$BACKUP_DIR/wg-backbone.conf.before" ]; then
    install -o root -g root -m 0600 "$BACKUP_DIR/wg-backbone.conf.before" "$WG_TMP" >/dev/null 2>&1 || true
    mv -f "$WG_TMP" "$WG_CONF" >/dev/null 2>&1 || true
  fi
  systemctl disable --now "$POLICY_UNIT_NAME" >/dev/null 2>&1 || true
  remove_policy_barrier
  rm -f "$AWG_DROPIN" "$POLICY_UNIT" "$POLICY_RUNTIME" "$SYSCTL_FILE"
  rmdir "$AWG_DROPIN_DIR" 2>/dev/null || true
  systemctl daemon-reload >/dev/null 2>&1 || true
  if ! systemctl is-active --quiet wg-quick@wg-backbone.service; then systemctl start wg-quick@wg-backbone.service >/dev/null 2>&1 || true; fi
  if ip link show "$WG_IF" >/dev/null 2>&1; then wg set "$WG_IF" peer "$KZ_PUBLIC_KEY" allowed-ips "$BASE_ALLOWED" >/dev/null 2>&1 || true; fi
  sysctl -w net.ipv4.ip_forward=0 >/dev/null 2>&1 || true
  sysctl -w net.ipv6.conf.all.forwarding=0 >/dev/null 2>&1 || true
  rollback_ok=1
  exact_policy_rule && rollback_ok=0
  ip -4 route show table "$TABLE_ID" 2>/dev/null | grep . >/dev/null && rollback_ok=0
  ufw_has_marker "$UFW_FORWARD_COMMENT" && rollback_ok=0
  ufw_has_marker "$UFW_DENY_COMMENT" && rollback_ok=0
  [ -e "$SYSCTL_FILE" ] && rollback_ok=0
  [ -e "$POLICY_RUNTIME" ] && rollback_ok=0
  [ -e "$POLICY_UNIT" ] && rollback_ok=0
  [ -e "$AWG_DROPIN" ] && rollback_ok=0
  if ip link show "$WG_IF" >/dev/null 2>&1; then
    [ "$(runtime_allowed_ips)" = "$BASE_ALLOWED" ] || rollback_ok=0
  fi
  if [ "$rollback_ok" -eq 1 ]; then rm -rf "$STATE_DIR"; else echo "ERROR: automatic rollback incomplete; managed state retained" >&2; fi
  exit "$rc"
}
trap cleanup EXIT

[ "${EUID:-$(id -u)}" -eq 0 ] || fail "run as root"
[[ "$SOURCE_HEAD" =~ ^[0-9a-f]{40}$ ]] || fail "VPS_TIER_SOURCE_HEAD must be a full lowercase commit SHA"
for cmd in awk bash cmp cut date dpkg grep head install ip iptables-save mktemp mv ping sed sha256sum sysctl systemctl ufw wg wg-quick; do require_cmd "$cmd"; done
host_ok || fail "host identity mismatch"
. /etc/os-release
[ "${ID:-}" = ubuntu ] && [ "${VERSION_CODENAME:-}" = "$EXPECTED_CODENAME" ] || fail "OS/suite mismatch"
[ "$(dpkg --print-architecture)" = amd64 ] || fail "architecture mismatch"
for source in "$POLICY_SOURCE" "$POLICY_UNIT_SOURCE" "$AWG_DROPIN_SOURCE"; do [ -r "$source" ] || fail "managed source missing: $source"; done
bash -n "$POLICY_SOURCE"
[ -r /var/lib/vps-tier/moscow-awg-client-termination/state.env ] || fail "accepted Stage-5 managed state missing"
[ -r /var/lib/vps-tier/wireguard-backbone/moscow/state.env ] || fail "managed backbone state missing"
[ ! -e "$STATE_DIR" ] || fail "Stage-6 managed state already exists"
[ ! -e "$SYSCTL_FILE" ] || fail "Stage-6 sysctl file already exists"
[ ! -e "$POLICY_RUNTIME" ] || fail "policy runtime path already exists"
[ ! -e "$POLICY_UNIT" ] || fail "policy unit already exists"
[ ! -e "$AWG_DROPIN" ] || fail "AWG fail-closed drop-in already exists"
systemctl is-active --quiet ufw.service || fail "ufw.service must be active"
systemctl is-active --quiet wg-quick@wg-backbone.service || fail "backbone unit inactive"
systemctl is-enabled --quiet wg-quick@wg-backbone.service || fail "backbone unit disabled"
systemctl is-active --quiet awg-quick@awg-client.service || fail "AWG client unit inactive"
systemctl is-enabled --quiet awg-quick@awg-client.service || fail "AWG client unit disabled"
[ "$(runtime_allowed_ips)" = "$BASE_ALLOWED" ] || fail "runtime backbone AllowedIPs are not at Stage-5 baseline"
grep -Fx "AllowedIPs = $BASE_ALLOWED" "$WG_CONF" >/dev/null || fail "persistent backbone AllowedIPs baseline mismatch"
[ "$(grep -c '^\[Peer\]$' "$WG_CONF")" = 1 ] || fail "unexpected backbone peer count"
grep -E '^[[:space:]]*(Table|PostUp|PreDown)[[:space:]]*=' "$WG_CONF" >/dev/null && fail "backbone config already contains routing lifecycle directives"
[ "$(sysctl -n net.ipv4.ip_forward)" = 0 ] || fail "Moscow IPv4 forwarding must be 0 before Stage 6"
[ "$(sysctl -n net.ipv6.conf.all.forwarding)" = 0 ] || fail "Moscow IPv6 forwarding must remain 0"
for key in all default "$WAN_IF" "$AWG_IF" "$WG_IF"; do [ "$(sysctl -n net.ipv4.conf.$key.rp_filter)" = 2 ] || fail "rp_filter must equal 2 for $key"; done
assert_no_forwarding_persistence
if ip -4 rule show | awk -v p="${RULE_PRIORITY}:" '$1==p {found=1} END{exit !found}'; then fail "policy priority already occupied"; fi
[ -z "$(ip -4 route show table "$TABLE_ID" 2>/dev/null || true)" ] || fail "policy table $TABLE_ID already contains routes"
if grep -RhsE "^[[:space:]]*${TABLE_ID}[[:space:]]+" /etc/iproute2/rt_tables /etc/iproute2/rt_tables.d 2>/dev/null | grep . >/dev/null; then fail "routing table ID $TABLE_ID already registered"; fi
ufw status | grep -x 'Status: active' >/dev/null || fail "UFW inactive"
ufw status verbose | grep -E '^Default: .*disabled \(routed\)' >/dev/null || fail "UFW routed default is not deny/disabled"
ufw_has_marker "$UFW_FORWARD_COMMENT" && fail "managed client-forward UFW rule already exists"
ufw_has_marker "$UFW_DENY_COMMENT" && fail "managed no-fallback UFW rule already exists"
ufw status numbered | grep -F "$CLIENT_SUBNET" >/dev/null && fail "unmanaged client-subnet routed UFW rule exists"
snapshot_nat | grep -F "$CLIENT_SUBNET" >/dev/null && fail "Moscow client NAT already exists"
ufw --dry-run route deny in on "$AWG_IF" out on "$WAN_IF" from "$CLIENT_SUBNET" comment "$UFW_DENY_COMMENT" >/dev/null
ufw --dry-run route allow in on "$AWG_IF" out on "$WG_IF" from "$CLIENT_SUBNET" comment "$UFW_FORWARD_COMMENT" >/dev/null
assert_required_units
ping -c 1 -W 2 "$KZ_TUNNEL_IP" >/dev/null || fail "backbone peer ping failed before Stage 6"

BACKUP_ID="$(date -u +%Y%m%dT%H%M%SZ)"
BACKUP_DIR="$BACKUP_ROOT/$BACKUP_ID"
mkdir -p "$BACKUP_DIR"; chmod 0700 "$BACKUP_DIR"
cp -a "$WG_CONF" "$BACKUP_DIR/wg-backbone.conf.before"
BASE_CONFIG_SHA="$(sha256sum "$WG_CONF" | awk '{print $1}')"
DEFAULT_ROUTE_BEFORE="$(ip -4 route show default)"
ip -4 route show table main > "$BACKUP_DIR/routes-main.before"
ip -4 rule show > "$BACKUP_DIR/rules.before"
snapshot_nat > "$BACKUP_DIR/nat.before"
snapshot_units "$BACKUP_DIR/units.before"
ufw status numbered > "$BACKUP_DIR/ufw.before"

TMP_DIR="$(mktemp -d /tmp/vps-tier-moscow-stage6.XXXXXX)"; chmod 0700 "$TMP_DIR"
TMP_CONF="$TMP_DIR/wg-backbone.conf"
POST_UP="PostUp = /usr/sbin/ip -4 route replace default dev $WG_IF table $TABLE_ID metric 10"
PRE_DOWN="PreDown = /usr/sbin/ip -4 route del default dev $WG_IF table $TABLE_ID metric 10 2>/dev/null || true"
awk -v allowed="AllowedIPs = $APPLIED_ALLOWED" -v table="Table = off" -v post="$POST_UP" -v pre="$PRE_DOWN" '
  BEGIN { peer=0; allowed_count=0; injected=0 }
  $0=="[Peer]" && injected==0 { print table; print post; print pre; print ""; injected=1; peer=1; print; next }
  peer==1 && $0=="AllowedIPs = 10.70.0.2/32" { print allowed; allowed_count++; next }
  { print }
  END { if (injected!=1 || allowed_count!=1) exit 42 }
' "$WG_CONF" > "$TMP_CONF"
chmod 0600 "$TMP_CONF"
wg-quick strip "$TMP_CONF" >/dev/null
grep -Fx "AllowedIPs = $APPLIED_ALLOWED" "$TMP_CONF" >/dev/null
grep -Fx "Table = off" "$TMP_CONF" >/dev/null
grep -Fx "$POST_UP" "$TMP_CONF" >/dev/null
grep -Fx "$PRE_DOWN" "$TMP_CONF" >/dev/null
APPLIED_CONFIG_SHA="$(sha256sum "$TMP_CONF" | awk '{print $1}')"

trap rollback_on_error ERR
mkdir -p "$STATE_DIR"; chmod 0700 "$STATE_DIR"
cat > "$STATE_FILE" <<STATE
owner=vps-tier
status=applying
source_head=$SOURCE_HEAD
backup_set=$BACKUP_DIR
wg_config_path=$WG_CONF
baseline_config_sha256=$BASE_CONFIG_SHA
applied_config_sha256=$APPLIED_CONFIG_SHA
client_subnet=$CLIENT_SUBNET
policy_table=$TABLE_ID
policy_priority=$RULE_PRIORITY
sysctl_file=$SYSCTL_FILE
policy_runtime=$POLICY_RUNTIME
policy_unit=$POLICY_UNIT
awg_dropin=$AWG_DROPIN
STATE
chmod 0600 "$STATE_FILE"

install -d -o root -g root -m 0755 /usr/local/libexec/vps-tier
install -o root -g root -m 0755 "$POLICY_SOURCE" "$POLICY_RUNTIME"
install -o root -g root -m 0644 "$POLICY_UNIT_SOURCE" "$POLICY_UNIT"
install -d -o root -g root -m 0755 "$AWG_DROPIN_DIR"
install -o root -g root -m 0644 "$AWG_DROPIN_SOURCE" "$AWG_DROPIN"
POLICY_FILES_INSTALLED=1
install -o root -g root -m 0600 "$TMP_CONF" "$WG_TMP"
mv -f "$WG_TMP" "$WG_CONF"; CONFIG_CHANGED=1
systemctl daemon-reload
systemctl enable --now "$POLICY_UNIT_NAME" >/dev/null; POLICY_STARTED=1
systemctl is-active --quiet "$POLICY_UNIT_NAME" || fail "policy barrier unit inactive"
systemctl is-enabled --quiet "$POLICY_UNIT_NAME" || fail "policy barrier unit disabled"
exact_policy_rule || fail "policy rule missing after barrier start"
ip -4 route show table "$TABLE_ID" | grep -E '^prohibit default.*metric 32760([[:space:]]|$)' >/dev/null || fail "prohibit fallback route missing"
wg set "$WG_IF" peer "$KZ_PUBLIC_KEY" allowed-ips "$APPLIED_ALLOWED"; WG_RUNTIME_CHANGED=1
ip -4 route replace default dev "$WG_IF" table "$TABLE_ID" metric 10
ufw route deny in on "$AWG_IF" out on "$WAN_IF" from "$CLIENT_SUBNET" comment "$UFW_DENY_COMMENT" >/dev/null; UFW_DENY_ADDED=1
ufw route allow in on "$AWG_IF" out on "$WG_IF" from "$CLIENT_SUBNET" comment "$UFW_FORWARD_COMMENT" >/dev/null; UFW_FORWARD_ADDED=1
cat > "$TMP_DIR/sysctl.conf" <<SYSCTL
# Managed by vps-tier: Moscow client fail-closed routing Stage 6
net.ipv4.ip_forward = 1
net.ipv6.conf.all.forwarding = 0
SYSCTL
install -o root -g root -m 0644 "$TMP_DIR/sysctl.conf" "$SYSCTL_FILE"; SYSCTL_CREATED=1
sysctl -w net.ipv4.ip_forward=1 >/dev/null; FORWARDING_CHANGED=1

[ "$(runtime_allowed_ips)" = "$APPLIED_ALLOWED" ] || fail "runtime backbone AllowedIPs validation failed"
exact_policy_rule || fail "policy rule disappeared"
ip -4 route show table "$TABLE_ID" | grep -E '^default dev wg-backbone.*metric 10([[:space:]]|$)' >/dev/null || fail "policy usable default route missing"
ip -4 route show table "$TABLE_ID" | grep -E '^prohibit default.*metric 32760([[:space:]]|$)' >/dev/null || fail "policy prohibit default missing"
ufw_has_marker "$UFW_DENY_COMMENT" || fail "no-fallback UFW rule missing"
ufw_has_marker "$UFW_FORWARD_COMMENT" || fail "client-forward UFW rule missing"
[ "$(sysctl -n net.ipv4.ip_forward)" = 1 ] || fail "IPv4 forwarding not enabled"
[ "$(sysctl -n net.ipv6.conf.all.forwarding)" = 0 ] || fail "IPv6 forwarding changed"
[ "$(ip -4 route show default)" = "$DEFAULT_ROUTE_BEFORE" ] || fail "Moscow default route changed"
ip -4 route show table main > "$BACKUP_DIR/routes-main.after"
cmp -s "$BACKUP_DIR/routes-main.before" "$BACKUP_DIR/routes-main.after" || fail "main routing table changed"
ROUTE_GET="$(ip -4 route get 1.1.1.1 from 10.71.0.2 iif "$AWG_IF")"
printf '%s\n' "$ROUTE_GET" | grep -F "dev $WG_IF" >/dev/null || fail "client policy lookup does not use backbone"
printf '%s\n' "$ROUTE_GET" | grep -F "table $TABLE_ID" >/dev/null || fail "client policy lookup does not use table $TABLE_ID"
snapshot_nat > "$BACKUP_DIR/nat.after"
cmp -s "$BACKUP_DIR/nat.before" "$BACKUP_DIR/nat.after" || fail "Moscow NAT table changed"
ping -c 1 -W 2 "$KZ_TUNNEL_IP" >/dev/null || fail "backbone ping failed after Stage 6"
LATEST_HANDSHAKE="$(wg show "$WG_IF" latest-handshakes | awk -v key="$KZ_PUBLIC_KEY" '$1==key {print $2}')"
[ -n "$LATEST_HANDSHAKE" ] && [ "$LATEST_HANDSHAKE" -gt 0 ] || fail "backbone handshake absent"
snapshot_units "$BACKUP_DIR/units.after"
cmp -s "$BACKUP_DIR/units.before" "$BACKUP_DIR/units.after" || fail "protected unit state changed"
assert_required_units
ufw status numbered > "$BACKUP_DIR/ufw.after"

cat > "$STATE_FILE" <<STATE
owner=vps-tier
status=applied
source_head=$SOURCE_HEAD
applied_at_utc=$BACKUP_ID
backup_set=$BACKUP_DIR
wg_config_path=$WG_CONF
baseline_config_sha256=$BASE_CONFIG_SHA
applied_config_sha256=$APPLIED_CONFIG_SHA
client_subnet=$CLIENT_SUBNET
policy_table=$TABLE_ID
policy_priority=$RULE_PRIORITY
sysctl_file=$SYSCTL_FILE
policy_runtime=$POLICY_RUNTIME
policy_unit=$POLICY_UNIT
awg_dropin=$AWG_DROPIN
ufw_forward_rule_owned=yes
ufw_no_fallback_rule_owned=yes
STATE
chmod 0600 "$STATE_FILE"
cat > "$EVIDENCE_FILE" <<EVIDENCE
# Moscow Fail-Closed Client Routing — Apply Evidence

- UTC: $(date -u +%Y-%m-%dT%H:%M:%SZ)
- Source Git HEAD: $SOURCE_HEAD
- Client subnet: $CLIENT_SUBNET
- Policy table: $TABLE_ID
- Policy priority: $RULE_PRIORITY
- Client policy lookup uses: $WG_IF
- Fail-closed prohibit default: present
- Backbone peer AllowedIPs widened for return Internet sources: $APPLIED_ALLOWED
- WireGuard automatic route management: disabled with Table=off
- UFW client to backbone forward: managed
- UFW client to Moscow public-interface fallback: explicit deny
- IPv4 forwarding: 1 managed and persistent
- IPv6 forwarding: 0 unchanged
- Moscow default route changed: no
- Moscow main routing table changed: no
- Moscow client NAT: absent
- Backbone ping/handshake after apply: passed
- Protected unit state changed: no
- Boot ordering: AWG requires UFW and fail-closed policy barrier
- End-to-end iPhone egress: deferred until client profile stage
- Backup set: $BACKUP_DIR
- Secrets recorded: no
EVIDENCE
chmod 0600 "$EVIDENCE_FILE"

trap - ERR
CONFIG_CHANGED=0; WG_RUNTIME_CHANGED=0; POLICY_FILES_INSTALLED=0; POLICY_STARTED=0
UFW_FORWARD_ADDED=0; UFW_DENY_ADDED=0; SYSCTL_CREATED=0; FORWARDING_CHANGED=0

echo "DONE: Moscow fail-closed client routing applied"
echo "CLIENT_SUBNET=$CLIENT_SUBNET"
echo "POLICY_TABLE=$TABLE_ID"
echo "POLICY_ROUTE=wg-backbone"
echo "PROHIBIT_FALLBACK=ready"
echo "UFW_FORWARD=ready"
echo "UFW_ETH0_FALLBACK=denied"
echo "IPV4_FORWARDING=1"
echo "MOSCOW_CLIENT_NAT=absent"
echo "END_TO_END_TEST=deferred"
echo "EVIDENCE_FILE=$EVIDENCE_FILE"
echo "BACKUP_SET=$BACKUP_DIR"
