#!/usr/bin/env bash
set -Eeuo pipefail

SOURCE_HEAD="${VPS_TIER_SOURCE_HEAD:-}"
EXPECTED_IPV4="194.32.142.88"
EXPECTED_CODENAME="jammy"
WG_IF="wg-backbone"
WAN_IF="enp3s0"
CLIENT_SUBNET="10.71.0.0/24"
PEER_BACKBONE_IP="10.70.0.1"
PEER_PUBLIC_KEY="tfSZHDDhIcgim4s6fujmel13vSvThM1Q5EAq/lK8kDQ="
TARGET_CONF="/etc/wireguard/wg-backbone.conf"
TARGET_TMP="${TARGET_CONF}.vps-tier.tmp"
WG_UNIT="wg-quick@wg-backbone.service"
STATE_DIR="/var/lib/vps-tier/kz-client-egress"
STATE_FILE="$STATE_DIR/state.env"
EVIDENCE_FILE="$STATE_DIR/evidence.md"
BACKUP_ROOT="/var/backups/vps-tier/kz-client-egress/apply"
UFW_COMMENT="vps-tier-kz-client-egress-forward"
NAT_COMMENT="vps-tier-kz-client-egress"
BASE_ALLOWED="10.70.0.1/32"
APPLIED_ALLOWED="10.70.0.1/32, 10.71.0.0/24"
APPLIED_ALLOWED_RUNTIME="10.70.0.1/32,10.71.0.0/24"
TMP_DIR=""
BACKUP_DIR=""
CONFIG_CHANGED=0
WG_CHANGED=0
ROUTE_ADDED=0
UFW_ADDED=0
NAT_ADDED=0

fail() { echo "ERROR: $*" >&2; return 1; }
require_cmd() { command -v "$1" >/dev/null 2>&1 || fail "missing command: $1"; }
host_ok() { ip -4 -o addr show scope global | awk '{print $4}' | cut -d/ -f1 | grep -Fx "$EXPECTED_IPV4" >/dev/null; }
ufw_has_marker() { ufw status numbered 2>/dev/null | grep -F "$UFW_COMMENT" >/dev/null; }
snapshot_nat() { iptables-save -t nat | sed -E '/^# (Generated by iptables-save|Completed on) /d'; }
snapshot_units() {
  out="$1"; : > "$out"
  for unit in ssh.service nginx.service docker.service xray.service hysteria-server.service cloudflared.service; do
    printf 'UNIT=%s\n' "$unit" >> "$out"
    systemctl show "$unit" -p LoadState -p ActiveState -p SubState -p MainPID --no-pager 2>/dev/null >> "$out" || true
  done
}
assert_required_units() {
  for unit in ssh.service nginx.service docker.service; do systemctl is-active --quiet "$unit" || fail "protected unit inactive: $unit"; done
}
nat_rule_exists() {
  iptables -t nat -C POSTROUTING -s "$CLIENT_SUBNET" -o "$WAN_IF" -m comment --comment "$NAT_COMMENT" -j SNAT --to-source "$EXPECTED_IPV4" 2>/dev/null
}
runtime_allowed_ips() {
  wg show "$WG_IF" dump | awk -F '\t' -v key="$PEER_PUBLIC_KEY" '$1==key {print $4}'
}
assert_no_client_subnet_overlap() {
  python3 -c '
import ipaddress, sys
target = ipaddress.ip_network(sys.argv[1], strict=False)
for raw in sys.stdin:
    value = raw.strip()
    if not value:
        continue
    try:
        network = ipaddress.ip_network(value, strict=False)
    except ValueError:
        continue
    if target.overlaps(network):
        print(f"ERROR: client subnet overlaps existing prefix {network}", file=sys.stderr)
        sys.exit(1)
' "$CLIENT_SUBNET" < <(
    ip -4 -o addr show | awk '{print $4}'
    ip -4 route show table all | awk '$1 ~ /^[0-9]+\./ {print $1}'
    for id in $(docker network ls -q); do
      docker network inspect -f '{{range .IPAM.Config}}{{.Subnet}}{{println}}{{end}}' "$id"
    done
  )
}
cleanup() { [ -z "$TMP_DIR" ] || rm -rf "$TMP_DIR"; rm -f "$TARGET_TMP"; }
rollback_on_error() {
  rc=$?; trap - ERR; set +e
  echo "ERROR: KZ client egress apply failed; reverting task-owned changes" >&2
  if [ "$NAT_ADDED" -eq 1 ]; then iptables -t nat -D POSTROUTING -s "$CLIENT_SUBNET" -o "$WAN_IF" -m comment --comment "$NAT_COMMENT" -j SNAT --to-source "$EXPECTED_IPV4"; fi
  if [ "$UFW_ADDED" -eq 1 ]; then ufw --force delete route allow in on "$WG_IF" out on "$WAN_IF" from "$CLIENT_SUBNET" >/dev/null 2>&1; fi
  if [ "$ROUTE_ADDED" -eq 1 ]; then ip route del "$CLIENT_SUBNET" dev "$WG_IF" 2>/dev/null; fi
  if [ "$WG_CHANGED" -eq 1 ]; then wg set "$WG_IF" peer "$PEER_PUBLIC_KEY" allowed-ips "$BASE_ALLOWED"; fi
  if [ "$CONFIG_CHANGED" -eq 1 ] && [ -r "$BACKUP_DIR/wg-backbone.conf.before" ]; then
    install -o root -g root -m 0600 "$BACKUP_DIR/wg-backbone.conf.before" "$TARGET_TMP"
    mv -f "$TARGET_TMP" "$TARGET_CONF"
  fi
  rollback_ok=1
  nat_rule_exists && rollback_ok=0
  ufw_has_marker && rollback_ok=0
  ip -4 route show table all | grep -F "$CLIENT_SUBNET" >/dev/null && rollback_ok=0
  wg show "$WG_IF" allowed-ips | grep -F "$CLIENT_SUBNET" >/dev/null && rollback_ok=0
  if [ "$rollback_ok" -eq 1 ]; then
    rm -rf "$STATE_DIR"
  else
    echo "ERROR: automatic rollback incomplete; managed state retained" >&2
  fi
  exit "$rc"
}
trap cleanup EXIT

[ "${EUID:-$(id -u)}" -eq 0 ] || fail "run as root"
[[ "$SOURCE_HEAD" =~ ^[0-9a-f]{40}$ ]] || fail "VPS_TIER_SOURCE_HEAD must be a full lowercase commit SHA"
for cmd in awk cmp cut date docker dpkg grep install ip iptables iptables-save mktemp mv ping python3 sed sha256sum sysctl systemctl ufw wg wg-quick; do require_cmd "$cmd"; done
host_ok || fail "host identity mismatch"
. /etc/os-release
[ "${ID:-}" = ubuntu ] && [ "${VERSION_CODENAME:-}" = "$EXPECTED_CODENAME" ] || fail "OS/suite mismatch"
[ "$(dpkg --print-architecture)" = amd64 ] || fail "architecture mismatch"
[ -r "$TARGET_CONF" ] || fail "backbone config missing"
[ -r /var/lib/vps-tier/wireguard-backbone/kazakhstan/state.env ] || fail "backbone managed state missing"
[ ! -e "$STATE_DIR" ] || fail "client-egress managed state already exists"
systemctl is-active --quiet "$WG_UNIT" || fail "backbone unit inactive"
systemctl is-enabled --quiet "$WG_UNIT" || fail "backbone unit disabled"
[ "$(sysctl -n net.ipv4.ip_forward)" = 1 ] || fail "IPv4 forwarding must already equal 1"
[ "$(sysctl -n net.ipv6.conf.all.forwarding)" = 0 ] || fail "IPv6 forwarding must remain 0"
[ "$(sysctl -n net.ipv4.conf.all.rp_filter)" = 2 ] || fail "all.rp_filter must equal 2"
[ "$(sysctl -n net.ipv4.conf.$WAN_IF.rp_filter)" = 2 ] || fail "$WAN_IF rp_filter must equal 2"
[ "$(sysctl -n net.ipv4.conf.$WG_IF.rp_filter)" = 2 ] || fail "$WG_IF rp_filter must equal 2"
ufw status | grep -x 'Status: active' >/dev/null || fail "UFW inactive"
iptables-save -t filter | grep -F 'ufw-before-forward' | grep -F 'RELATED,ESTABLISHED' >/dev/null || fail "UFW established-forward rule absent"
assert_required_units

RUNTIME_ALLOWED_BEFORE="$(runtime_allowed_ips)"
[ "$RUNTIME_ALLOWED_BEFORE" = "$BASE_ALLOWED" ] || fail "runtime peer AllowedIPs are not at the exact approved baseline"
grep -Fx "AllowedIPs = $BASE_ALLOWED" "$TARGET_CONF" >/dev/null || fail "persistent baseline AllowedIPs mismatch"
grep -F "$CLIENT_SUBNET" "$TARGET_CONF" >/dev/null && fail "client subnet already in backbone config"
assert_no_client_subnet_overlap || fail "client subnet overlaps current host/route/Docker state"
ufw_has_marker && fail "managed UFW forward rule already exists"
ufw status numbered | grep -F "$CLIENT_SUBNET" >/dev/null && fail "unmanaged UFW client-subnet rule exists"
snapshot_nat | grep -F "$NAT_COMMENT" >/dev/null && fail "managed NAT rule already exists"
snapshot_nat | grep -F "$CLIENT_SUBNET" >/dev/null && fail "unmanaged client-subnet NAT rule exists"
ufw --dry-run route allow in on "$WG_IF" out on "$WAN_IF" from "$CLIENT_SUBNET" comment "$UFW_COMMENT" >/dev/null

BACKUP_ID="$(date -u +%Y%m%dT%H%M%SZ)"
BACKUP_DIR="$BACKUP_ROOT/$BACKUP_ID"
mkdir -p "$BACKUP_DIR"
chmod 0700 "$BACKUP_DIR"
cp -a "$TARGET_CONF" "$BACKUP_DIR/wg-backbone.conf.before"
BASE_CONFIG_SHA="$(sha256sum "$TARGET_CONF" | awk '{print $1}')"
DEFAULT_ROUTE_BEFORE="$(ip -4 route show default)"
snapshot_nat > "$BACKUP_DIR/nat.before"
snapshot_units "$BACKUP_DIR/units.before"
ufw status numbered > "$BACKUP_DIR/ufw.before"

TMP_DIR="$(mktemp -d /tmp/vps-tier-kz-client-egress.XXXXXX)"
TMP_CONF="$TMP_DIR/wg-backbone.conf"
POST_UP="PostUp = iptables -t nat -C POSTROUTING -s $CLIENT_SUBNET -o $WAN_IF -m comment --comment $NAT_COMMENT -j SNAT --to-source $EXPECTED_IPV4 || iptables -t nat -A POSTROUTING -s $CLIENT_SUBNET -o $WAN_IF -m comment --comment $NAT_COMMENT -j SNAT --to-source $EXPECTED_IPV4"
PRE_DOWN="PreDown = iptables -t nat -C POSTROUTING -s $CLIENT_SUBNET -o $WAN_IF -m comment --comment $NAT_COMMENT -j SNAT --to-source $EXPECTED_IPV4 && iptables -t nat -D POSTROUTING -s $CLIENT_SUBNET -o $WAN_IF -m comment --comment $NAT_COMMENT -j SNAT --to-source $EXPECTED_IPV4 || true"
awk -v allowed="AllowedIPs = $APPLIED_ALLOWED" -v post="$POST_UP" -v pre="$PRE_DOWN" '
  BEGIN { replaced=0; inserted=0 }
  $0=="AllowedIPs = 10.70.0.1/32" { print allowed; replaced++; next }
  $0=="[Peer]" { if (inserted==0) { print post; print pre; print ""; inserted++ } print; next }
  { print }
  END { if (replaced!=1 || inserted!=1) exit 42 }
' "$TARGET_CONF" > "$TMP_CONF"
chmod 0600 "$TMP_CONF"
wg-quick strip "$TMP_CONF" >/dev/null
grep -Fx "AllowedIPs = $APPLIED_ALLOWED" "$TMP_CONF" >/dev/null
grep -Fx "$POST_UP" "$TMP_CONF" >/dev/null
grep -Fx "$PRE_DOWN" "$TMP_CONF" >/dev/null

mkdir -p "$STATE_DIR"; chmod 0700 "$STATE_DIR"
trap rollback_on_error ERR
install -o root -g root -m 0600 "$TMP_CONF" "$TARGET_TMP"
mv -f "$TARGET_TMP" "$TARGET_CONF"; CONFIG_CHANGED=1
wg set "$WG_IF" peer "$PEER_PUBLIC_KEY" allowed-ips "$BASE_ALLOWED","$CLIENT_SUBNET"; WG_CHANGED=1
ip route add "$CLIENT_SUBNET" dev "$WG_IF"; ROUTE_ADDED=1
ufw route allow in on "$WG_IF" out on "$WAN_IF" from "$CLIENT_SUBNET" comment "$UFW_COMMENT" >/dev/null; UFW_ADDED=1
iptables -t nat -A POSTROUTING -s "$CLIENT_SUBNET" -o "$WAN_IF" -m comment --comment "$NAT_COMMENT" -j SNAT --to-source "$EXPECTED_IPV4"; NAT_ADDED=1

[ "$(runtime_allowed_ips)" = "$APPLIED_ALLOWED_RUNTIME" ] || fail "runtime AllowedIPs validation failed"
ip -4 route show "$CLIENT_SUBNET" | grep -F "dev $WG_IF" >/dev/null || fail "client return route missing"
ufw_has_marker || fail "UFW routed allow validation failed"
nat_rule_exists || fail "SNAT validation failed"
[ "$(ip -4 route show default)" = "$DEFAULT_ROUTE_BEFORE" ] || fail "default route changed"
[ "$(sysctl -n net.ipv4.ip_forward)" = 1 ] || fail "IPv4 forwarding changed"
[ "$(sysctl -n net.ipv6.conf.all.forwarding)" = 0 ] || fail "IPv6 forwarding changed"
ping -c 1 -W 2 "$PEER_BACKBONE_IP" >/dev/null || fail "backbone peer ping failed"
LATEST_HANDSHAKE="$(wg show "$WG_IF" latest-handshakes | awk -v key="$PEER_PUBLIC_KEY" '$1==key {print $2}')"
[ -n "$LATEST_HANDSHAKE" ] && [ "$LATEST_HANDSHAKE" -gt 0 ] || fail "WireGuard handshake absent"

snapshot_nat > "$BACKUP_DIR/nat.after"
grep -v -F "$NAT_COMMENT" "$BACKUP_DIR/nat.after" > "$BACKUP_DIR/nat.after.without-owned"
cmp -s "$BACKUP_DIR/nat.before" "$BACKUP_DIR/nat.after.without-owned" || fail "unexpected NAT mutation outside owned SNAT rule"
snapshot_units "$BACKUP_DIR/units.after"
cmp -s "$BACKUP_DIR/units.before" "$BACKUP_DIR/units.after" || fail "protected unit state changed"
assert_required_units
ufw status numbered > "$BACKUP_DIR/ufw.after"
APPLIED_CONFIG_SHA="$(sha256sum "$TARGET_CONF" | awk '{print $1}')"

cat > "$STATE_FILE" <<STATE
owner=vps-tier
source_head=$SOURCE_HEAD
applied_at_utc=$BACKUP_ID
backup_set=$BACKUP_DIR
wg_interface=$WG_IF
wan_interface=$WAN_IF
client_subnet=$CLIENT_SUBNET
before_config_sha256=$BASE_CONFIG_SHA
applied_config_sha256=$APPLIED_CONFIG_SHA
persistent_allowed_ips=yes
return_route=yes
ufw_forward_rule=yes
snat_rule=yes
STATE
chmod 0600 "$STATE_FILE"
cat > "$EVIDENCE_FILE" <<EVIDENCE
# Kazakhstan Client Egress — Apply Evidence

- UTC: $(date -u +%Y-%m-%dT%H:%M:%SZ)
- Source Git HEAD: $SOURCE_HEAD
- Host IPv4: $EXPECTED_IPV4
- Client subnet: $CLIENT_SUBNET
- Backbone interface: $WG_IF
- Internet interface: $WAN_IF
- Peer AllowedIPs extended for client subnet: yes
- Persistent return route via WireGuard config: yes
- Runtime return route: yes
- UFW routed allow from client subnet to Internet interface: yes
- Explicit SNAT source: $EXPECTED_IPV4
- SNAT persistence bound to wg-quick PostUp/PreDown: yes
- IPv4 forwarding changed: no (remains 1)
- IPv6 forwarding changed: no (remains 0)
- Default route changed: no
- Unexpected NAT mutation: no
- Backbone ping/handshake after apply: passed
- Protected unit state changed: no
- End-to-end client egress test: deferred until Moscow client routing exists
- Backup set: $BACKUP_DIR
- Secrets recorded: no
EVIDENCE
chmod 0600 "$EVIDENCE_FILE"

trap - ERR
CONFIG_CHANGED=0; WG_CHANGED=0; ROUTE_ADDED=0; UFW_ADDED=0; NAT_ADDED=0
echo "DONE: Kazakhstan client egress forwarding/SNAT prepared"
echo "CLIENT_SUBNET=$CLIENT_SUBNET"
echo "RETURN_ROUTE=ready"
echo "UFW_FORWARD=ready"
echo "SNAT=ready"
echo "END_TO_END_TEST=deferred"
echo "EVIDENCE_FILE=$EVIDENCE_FILE"
echo "BACKUP_SET=$BACKUP_DIR"
